name: CICD
on: 
  push:
    branches:
      - main

jobs:
  buildkit:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: run BuildKit
        run: |
          cd bulletin-board
          buildctl build --frontend=gateway.v0  --opt source=kiamol/buildkit-buildpacks--local context=src --output type=image,name=kiamol/ch11-bulletin-board:buildkit
